services:
  node-frontend:
    container_name: node-frontend
    build:
      context: .
      dockerfile: etc/dev/node/Dockerfile-development-environment
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true


#  prodection-envirment:
#    container_name: nginx-prodection-envirment
#    build:
#      context: .
#      dockerfile: etc/prod/Dockerfile-production-environment
#    restart: unless-stopped
#    volumes:
#      - ./:/var/www/html/public:rw
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#    ports:
#      - 8080:80
